mysite/clothes/urls.py
from django.urls import path
from clothes import views

app_name = 'clothes'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('products/',views.products, name='products'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clothes/', include('clothes.urls')),
]

mysite/clothes/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    category_name = models.CharField(max_length = 30)

    def __str__(self):
        return self.category_name
    
class Item(models.Model):
    com_owner = models.ForeignKey(
        User,
        on_delete = models.CASCADE,
        default = 1
    )
    prod_code = models.IntegerField(default = 50)
    for_user = models.CharField(
        max_length = 100,
        default = 'ClothOwner'
    )
    item_name = models.CharField(max_length = 100)
    item_desc = models.CharField(max_length = 500)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length = 1000,
        default = 'https://th.bing.com/th/id/OIP.rg_dE8HiSUNjMwZHNHz_8AHaHa?rs=1&pid=ImgDetMain'
    )
    item_category = models.ForeignKey(Category,on_delete = models.CASCADE, default=1)
    featured_product = models.BooleanField(default = False)

    def __str__(self):
        return self.item_name

mysite/clothes/views.py
from django.shortcuts import render
from clothes.models import Item

# Create your views here.
def home(request):
    items = Item.objects.all()
    productlist = Item.objects.filter(featured_product=True)

    context = {
        'items': items,
        'productlist': productlist
    }
    return render(request,'clothes/home.html', context)

def products(request):

    if request.user.is_superuser:
        itemlist = Item.objects.all()

        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
        

    elif request.user.is_authenticated and request.user.profile.user_type == 'com_owner':
        itemlist = Item.objects.filter(com_owner = request.user.id)
        
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(com_owner = request.user.id, item_name__icontains=item_name)

    elif request.user.is_authenticated and request.user.profile.user_type == 'cust':
        itemlist = Item.objects.all()
        # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)


    else:
        itemlist = Item.objects.all()
                 # for search functionality
        item_name = request.GET.get('item_name')
        if item_name != '' and item_name is not None:
            itemlist = Item.objects.filter(item_name__icontains=item_name)
    context = {
        'itemlist':itemlist
    }
    return render(request, 'clothes/products.html',context)

mysite/templates/clothes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
       
       nav {
            height: 80px;
            box-shadow: 0px 10px 10px 0px black;
            background-image: url('{% static "clothes/fashion.jpg" %}');
        }
/*                                           NAVBAR-BRAND THAT IS THE BRAND NAME                                                                                 */
        .navbar-brand {
            color: black;
            font-weight: bold;
            text-shadow: 2px 2px 8px black;
            font-size: x-large;
        }

        .navbar-brand:hover {
            text-shadow: 2px 8px 2px 8px black;
            color: black;
        }

        .navs {
            margin-right: 10px;
            background-color: black;
            color: white;

        }

        .navs:hover {      
            color: white;
        }

/*                                           DROPDOWN CONTENTS                                                                                                       */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        /* Dropdown Content (Hidden by Default) */
        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            z-index: 1;
        }

        /* Links inside the dropdown */
        .dropdown-content a {
            /* color: gray; */
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        /* Change color of dropdown links on hover */
        .dropdown-content a:hover {
            background-color: rgb(98, 139, 189);
            color: black
        }

        /* Show the dropdown menu on hover */
        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* SEARCH FUNCTIONALIY */
        .search-bar{
            background: white;
            width: 100%;
            max-width: 700px;
            display: flex;
            border-radius: 60px;
        }
        .search-bar input{
            background: transparent;
            flex: 1;
            border: 0;
            outline: none;
            padding-left: 12px;
            padding-right: 12px;
            font-size: 20px;
            color: #cac7ff;
        }
        ::placeholder{
            color: black;
        }
        .search-bar button img{
            width: 25px;
            padding: 2px;
        }
        .search-bar button{
            border: 0;
            border-radius: 50%;
            width: 40px;
            height: 40px;
            background: #58629b;
            cursor: pointer;
        }







    </style>
</head>
<body>

    <nav class="navbar">
        <a href="{% url 'clothes:home' %}" class="navbar-brand">Fashion Trends</a>

         <!-- for search functionality -->
         <div class="search-box">
            <form action="{% url 'clothes:products' %}" method="GET" class="search-bar" >
                {% csrf_token %}
                <!-- <span><b style="color: white;" >Search: </b></span> -->
                <input type="search" name="item_name" placeholder="search anything">
                <button type="submit"><img src="{% static 'clothes/search.png' %}" alt="" srcset=""></button>
            </form>
        </div>

        <div class="navbar">
            {% if user.is_superuser %}
            <a href="{% url 'profile' %}" class="nav-item nav-link btn navs">Profile <i class="fa-regular fa-user"></i></a>
            <a href="{% url 'clothes:add_item' %}" class="nav-item nav-link btn navs">Add Item</a>

            <div class="dropdown">
                <button class="nav-item nav-link btn navs">Categories ↓</button>
                <div class="dropdown-content">
                <a href="{% url 'clothes:products'  %}">All Products</a>
                  <a href="{% url 'clothes:categories' 1 %}">Shirts</a>
                  <a href="{% url 'clothes:categories' 2 %}">T-Shirts</a>
                  <a href="{% url 'clothes:categories' 3 %}">Trousers</a>
                  <a href="{% url 'clothes:categories' 4 %}">Shoes</a>
                </div>
            </div>
            <a href="{% url 'logout' %}" class="nav-item nav-link btn navs">Logout <i class="fa-solid fa-right-to-bracket"></i></a>
            {% elif user.is_authenticated and user.profile.user_type == 'cust' %}
            <a href="{% url 'profile' %}" class="nav-item nav-link btn navs">Profile <i class="fa-regular fa-user"></i></a>

            <div class="dropdown">
                <button class="nav-item nav-link btn navs">Categories ↓</button>
                <div class="dropdown-content">
                <a href="{% url 'clothes:products'  %}">All Products</a>
                  <a href="{% url 'clothes:categories' 1 %}">Shirts</a>
                  <a href="{% url 'clothes:categories' 2 %}">T-Shirts</a>
                  <a href="{% url 'clothes:categories' 3 %}">Trousers</a>
                  <a href="{% url 'clothes:categories' 4 %}">Shoes</a>
                </div>
            </div>
            <a href="{% url 'logout' %}" class="nav-item nav-link btn navs">Logout <i class="fa-solid fa-right-to-bracket"></i></a>
            <a class="btn navs" href="{% url 'clothes:view_cart' %}">Your Cart<i class="fa-solid fa-cart-plus"></i></a>
            <a class="btn navs" href="{% url 'clothes:checkout' %}">Checkout<i class="fa-solid fa-cart-shopping"></i></a>
            

            {% elif user.is_authenticated and user.profile.user_type == 'com_owner' %}
            <a href="{% url 'profile' %}" class="nav-item nav-link btn navs">Profile <i class="fa-regular fa-user"></i></a>

            <div class="dropdown">
                <button class="nav-item nav-link btn navs">Categories ↓</button>
                <div class="dropdown-content">
                <a href="{% url 'clothes:products'  %}">All Products</a>
                  <a href="{% url 'clothes:categories' 1 %}">Shirts</a>
                  <a href="{% url 'clothes:categories' 2 %}">T-Shirts</a>
                  <a href="{% url 'clothes:categories' 3 %}">Trousers</a>
                  <a href="{% url 'clothes:categories' 4 %}">Shoes</a>
                </div>
            </div>
            <a href="{% url 'logout' %}" class="nav-item nav-link btn navs">Logout <i class="fa-solid fa-right-to-bracket"></i></a>
        
           

            {% else %}
                <a href="{% url 'signup' %}" class="nav-item nav-link btn navs">Sign Up <i class="fa-solid fa-user-plus"></i></a>
                <a href="{% url 'login' %}" class="nav-item nav-link btn navs">Login <i class="fa-solid fa-right-to-bracket"></i></a>
            {% endif %}
        </div>
    </nav>

   
    {% if messages %}

        {% for message in messages %}

            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>

        {% endfor %}


    {% endif %}

    <div class="mb-5">

    </div>


    {% block body %}
    {% endblock %}

</body>
</html>

mysite/templates/clothes/products.html
{% extends 'clothes/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block body %}
<div class="row">
    {% for item in itemlist %}
    <div class="col-3">
        <div class="offset-md-2 lg-4 row mt-5">
            <img src="{{ item.item_image }}" class="card" height="300px" width="250px" >
        </div>

        <div class="row mt-5 ml-5">
            <h3 style="font-size: 1.5rem;">{{ item.item_name }}</h3>
            <h5 style="font-style: italic; font-size: 1rem;">{{ item.item_desc | truncatewords:10 }}</h5>
            <h6>₹ {{ item.item_price }}</h6><br>
            <h6 style="font-style: italic;">Added For:{{ item.for_user }}</h6>
        </div>

        <div class="row mt-5 ml-5 mb-5">
            <a href="{% url 'clothes:detail' item.id %}" style="width: 100px; background: rgb(96,134,187); color: white;" class="btn">
                Details
            </a>

            {% if user.is_authenticated and user.profile.user_type == 'cust' %}
                <form action="{% url 'clothes:add_to_cart' item.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" style="width: 150px; background: rgb(96,134,187); color: white;" class="btn ml-2">Add to Cart</button>
                  </form>
            {% endif %}
        </div>

    </div>

    {% endfor %}
</div>

  
    {% endblock %}
</body>
</html>